-- ==============================================================================
-- MariFlow SaaS Seed Data for Development & Testing
-- ==============================================================================

-- Note: In production Supabase, `auth.users` IDs are generated by Supabase Auth.
-- This seed file can be executed after creating demo users or in local Supabase CLI.

-- Sample comment placeholder
-- Insert demo workspace if user exists:
-- INSERT INTO public.workspaces (id, name, slug, description, owner_id) ...
